version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order:
    build: ./order-service
    container_name: order_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"

  email:
    build: ./email-service
    container_name: email_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  inventory:
    build: ./inventory-service
    container_name: inventory_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  logger:
    build: ./logger-service
    container_name: logger_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment:
    build: ./payment-service
    container_name: payment_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  sms:
    build: ./sms-service
    container_name: sms_service
    depends_on:
      rabbitmq:
        condition: service_healthy
